---
title: "Data Manipulation"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
library(haven)
```

Let's import the `FAS_litters.csv` csv.

```{r}
litters_df=
  read_csv('data/FAS_litters.csv')
litters_df=
  janitor::clean_names(litters_df)
```


absolute directory!
```{r}
litter_df=read.csv('~/Columbia/ds/data_wrangling/data/FAS_litters.csv')
litter_df=read.csv('C:/Users/ariaw/Documents/Columbia/ds/data_wrangling/data/FAS_litters.csv')

```

```{r}
pups_df=
  read_csv('data/FAS_pups.csv')
pups_df=
  janitor::clean_names(pups_df)
```

```{r}
litters_df
head(litters_df)
tail(litters_df)
```

```{r,eval=FALSE}
view(litetrs_df)
```


```{r}
str(litters_df)
skimr::skim(litters_df)
```

```{r}
litters_df=read_csv(
  'data/FAS_litters.csv',
  skip=10,
  col_names=FALSE,
  na=c('NA',19),
  col_types=
    cols(
      "GD0 weight"=col_character()
    ))
```


```{r}
mlb_df=
  read_excel('data/mlb11.xlsx')
```


```{r}
pulse_df=
  read_sas('data/public_pulse_data.sas7bdat')

```

```{r,eval=FALSE}
litters_df=
  read.csv('data/FAS_litters.csv')
```

```{r}
litters_df=
  read_csv('data/FAS_litters.csv')
litters_df=
  janitor::clean_names(litters_df)
```

export data
```{r}
write_csv(litters_df,"data/litters_cleaned.csv")
```










```{r}
select(litters_df,group,litter_number,gd0_weight)

select(litters_df,gd0_weight,group)

select(litters_df,group,gd0_weight: gd_of_birth)

select(litters_df,group,starts_with('pups'))

select(litters_df,-litter_number)

select(litters_df,group,litter_id=litter_number,everything())
select(litters_df,gd0_weight,everything())
```


```{r}
rename(litters_df,litter_id=litter_number)
relocate(litters_df,litter_number)
```

```{r}
select(litters_df, group)
pull(litters_df, group)

```

```{r}
filter(litters_df,group=="Con7" )

filter(litters_df,group=="Con7" | group=='Con8')

filter(litters_df,group%in% c("Con7","Con8"))
```

```{r}
mutate(litters_df,wt_gain = gd18_weight - gd0_weight,group=str_to_lower(group))

```

```{r}

arrange(litters_df,gd0_weight)
arrange(litters_df,group,gd0_weight)


```


```{r}
libeary(tidyverse)
pulse_df=
  read_sas('data/public_pulse_data.sas7bdat')|>
  janitor::clean_names()|>
  pivot_longer

```



